### ISSUE TITLE
ImportError: cannot import name 'Ipware' from 'ipware'

### ISSUE THREAD

**Issue by AakrutiPatel** [un33k/python-ipware#7]
```
macOS 13

Python 3.12.0

Django 4.2.6

python-ipware 1.0.3
```

1, If use:

```
from ipware import Ipware

ipware = Ipware()
```

The following error message appears:

```
ImportError: cannot import name 'Ipware' from 'ipware' (/Users/user/www/venv_rest/lib/python3.12/site-packages/ipware/__init__.py). Did you mean: 'IpWare'?
```

2, If use:

```
import ipware

ipware = ipware.Ipware()
```

The following error message appears:

```
AttributeError: module 'ipware' has no attribute 'Ipware'. Did you mean: 'IpWare'?
```

3, If use:

```
import ipware

ipware = Ipware()
```

The following error message appears:

```
NameError: name 'Ipware' is not defined. Did you mean: 'ipware'?
```

**Comment by un33k** [comment]
@AakrutiPatel  Unfortunately both `django-ipware` and `python-ipware` published the package as `ipware`. 

Step to fix:  

1. Remove `django-ipware` from your requirements and uninstall it. (deprecated)
2. Add `python-ipware` to your requirements and install it again

The above will fix your error.

Note: The step 3) use case is not a valid python.

**Comment by AakrutiPatel** [comment]
I didn't install "django-ipware".

Now I use a clean Linux system to test. OS: Debian 12

The steps are as follows:

```py
user@debian:~$ uname -r
6.1.0-11-amd64

user@debian:~$ sudo apt-get install python3 python3-pip python3-venv

user@debian:~$ python3 -V
Python 3.11.2

user@debian:~$ python3 -m venv venv_test

user@debian:~$ cd venv_test/

user@debian:~/venv_test$ source ./bin/activate

(venv_test) user@debian:~/venv_test$ pip3 install python-ipware

(venv_test) user@debian:~/venv_test$ pip3 list
Package       Version
------------- -------
pip           23.0.1
python-ipware 1.0.3
setuptools    66.1.1

(venv_test) user@debian:~/venv_test$ touch ip.py

(venv_test) user@debian:~/venv_test$ ls
bin  include  ip.py  lib  lib64  pyvenv.cfg
```

1, If the content of `ip.py` is:

```py
from ipware import Ipware

ipware = Ipware()
```

```py
(venv_test) user@debian:~/venv_test$ python3 ip.py
Traceback (most recent call last):
  File "/home/user/venv_test/ip.py", line 1, in <module>
    from ipware import Ipware
ImportError: cannot import name 'Ipware' from 'ipware' (/home/user/venv_test/lib/python3.11/site-packages/ipware/__init__.py)
```


2, If the content of `ip.py` is:

```py
import ipware

ipware = ipware.Ipware()
```

```py
(venv_test) user@debian:~/venv_test$ python3 ip.py
Traceback (most recent call last):
  File "/home/user/venv_test/ip.py", line 7, in <module>
    ipware = ipware.Ipware()
             ^^^^^^^^^^^^^
AttributeError: module 'ipware' has no attribute 'Ipware'. Did you mean: 'IpWare'?
```

**Comment by un33k** [comment]
@AakrutiPatel  I see, the readme had a typing error.  It should be case sensitive:

```python
from ipware import IpWare

ipware = IpWare()
```

Readme updated. Thank you.
